export const REQUEST_KEY_DOWN = "REQUEST_KEY_DOWN";
export const REQUEST_KEY_UP = "REQUEST_KEY_UP";
export const REQUEST_KEY_LEFT = "REQUEST_KEY_LEFT";
export const REQUEST_KEY_RIGHT = "REQUEST_KEY_RIGHT";

export const REQUEST_KEY_LEFT_UP = "REQUEST_KEY_LEFT_UP";
export const REQUEST_KEY_LEFT_DOWN = "REQUEST_KEY_LEFT_DOWN";
export const REQUEST_KEY_RIGHT_UP = "REQUEST_KEY_RIGHT_UP";
export const REQUEST_KEY_RIGHT_DOWN = "REQUEST_KEY_RIGHT_DOWN";

export const LEFT_KEY = 37;
export const UP_KEY = 38;
export const RIGHT_KEY = 39;
export const DOWN_KEY = 40;
